version: '3'
services:
  proxy:
    container_name: proxy
    hostname: proxy
    image: nginx:latest
    ports:
      - '80:80' # common web
      - '443:443' # https
      - '4040:4040' # graphql
      - '5000:5000' # (dev)localhost cinesopa proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/web.conf:/etc/nginx/web.conf:ro
      - ./proxy/config:/etc/nginx/config:ro
      - ./proxy/common:/etc/nginx/common:ro
      - /etc/letsencrypt:/etc/ssl/private/letsencrypt:ro
      - ./server/config:/etc/ssl/private/server/config
    depends_on:
      - web
  web:
    image: eszqsc112/cinesopa:latest
    hostname: web
    ports:
      - '4000:4000'
    volumes:
      - /etc/letsencrypt:/app/server/config/letsencrypt:ro
      - ./server/config/common:/app/server/config/common:ro
      - ./server/config/mailer-credentials.json:/app/server/config/mailer-credentials.json:ro
      - ./server/uploads:/app/server/uploads
      - ./server/pdf-output:/app/server/pdf-output
    environment:
      - COMPOSE_DOCKER_CLI_BUILD=1
      - DOCKER_BUILDKIT=1
